[workspace]
members = ["app", "render"]

[package]
name = "render_test_2d"
version = "0.1.0"
edition = "2024"

[dependencies]
app = { path = "./app" }

[profile.release]
lto = "fat"
codegen-units = 1
strip = true
