[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
render = { path = "../render" }
bevy_ecs = "0.16.1"
bevy_transform = "0.16.1"
derive_more = { version = "2.0.1", features = ["deref", "deref_mut"] }
