[package]
name = "render"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.23.1"
glam = { version = "0.29.3", features = ["bytemuck"] }
pollster = "0.4.0"
wgpu = "26.0.1"
winit = "0.30.12"
